  - name: Remove container {{ dest_docker_path }}
    community.docker.docker_compose_v2:
      project_src: "{{ dest_docker_path }}"
      state: absent

  - name: Remove image {{ container_name }}:{{ container_tag }}
    community.docker.docker_image:
      state: absent
      name: "{{ container_name }}"
      tag: "{{ container_tag }}"