ungrouped:
  children:
    runners:
      hosts:
        192.168.1.204:
          ansible_user: piotr
          ansible_password:  "{{ lookup('env', 'LSRV01PASSWD') }}"
    lsrv-01:
      hosts:
        192.168.1.201:
          ansible_user: piotr
          ansible_become_pass: "{{ lookup('env', 'LSRV01PASSWD') }}"
          ansible_password: "{{ lookup('env', 'LSRV01PASSWD') }}"
    virt-group-01:
      hosts:
        192.168.1.201:
          ansible_user: piotr
          ansible_become_pass: "{{ lookup('env', 'LSRV01PASSWD') }}"
          ansible_password: "{{ lookup('env', 'LSRV01PASSWD') }}"