---
- name: Instal HomeAssistance on Docker
  hosts: runners
  become: true  # Run tasks with sudo privileges

  tasks:
  - name: 'Run shell command'
    shell: 'hostname'
    register: shell_output

  - name: 'Print shell command output'
    debug:
      msg: "{{ shell_output.stdout }}"