---
- name: Maintain runners daily tasks
  hosts: runners
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      tags: update

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
      tags: update
