---
- name: Maintain runners daily tasks
  hosts: runners
  gather_facts: yes
  #become: yes  # This ensures that Ansible will escalate privileges to sudo (or equivalent) when necessary
  #become_method: sudo

  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: safe
        update_cache: yes
        autoclean: true
        autoremove: true
      become: yes
