# This is a workflow for Home Assistant installation

name: Github Runner - HomeAssistant install

# Controls when the workflow will run	
on:	
  # Triggers the workflow on push or pull request events but only for the "main" branch	
  # push:	

  # Allows you to run this workflow manually from the Actions tab	
  workflow_dispatch:

jobs:	

  build:	
    # The type of runner that the job will run on	
    runs-on: self-hosted	

    env:	
      ANSIBLE_PATH: './ansible'	
      ANSIBLE_VENV_NAME: 'ansible_venv'	
      LSRV01PASSWD: ${{ secrets.LSRV01_PASSWD }}	
      VERBOSITY: '-v'	

    # Steps represent a sequence of tasks that will be executed as part of the job	
    steps:	
      # Synchronize files with repository	
      - name: Checkout	
        uses: actions/checkout@v4	

      # - name: Display host informations	
      #   run: |	
      #     echo "Verbosity level: $VERBOSITY"	
      #     echo Uptime:	
      #     uptime	
      #     echo ls -la	
      #     ls -la	
      #     echo "Pass: $LSRV01PASSWD"	

      - name: Check pip version	
        run: |	
          sudo apt-get update	
          sudo apt-get install python3-pip sshpass -y	
        #ssh-keyscan -p 22 192.168.1.204 >> ~/.ssh/known_hosts	

      - name: Set up Python	
        uses: actions/setup-python@v2	
        with:	
          python-version: '3.10.12'	

      - name: Create virtual environment	
        run: python -m venv $ANSIBLE_VENV_NAME	

      - name: Activate virtual environment	
        run: |	
          source $ANSIBLE_VENV_NAME/bin/activate	

      - name: Upgrade pip	
        run: pip install --upgrade pip	

      - name: Install Ansible Dependencies	
        run: pip install -r ./ansible/requirements.txt	

      - name: Display Ansible inventory	
        run: |	
         cd $ANSIBLE_PATH	
         ansible-inventory -i ./inventory/inventory.yml --list	
          
      # - name: Run ansible PING module for homeassistant host(s)	
      #   run: |	
      #    cd $ANSIBLE_PATH	
      #    ansible -i ./inventory/inventory.yml homeassistant -m ping $VERBOSITY	
          
      # - name: List files in ansible folder	
      #   run: |	
      #     #cd $ANSIBLE_PATH	
      #     ls	
      #     #tree	

      - name: Run ansible playbook for HomeAssistant installation (docker)
        run: |	
          cd $ANSIBLE_PATH	
          ansible-playbook ansible-install-ha.yaml -i ./inventory/inventory.yml  $VERBOSITY	
      
      # - name: Remove virtual environment	
      #   run: sudo rm -rf $ANSIBLE_VENV_NAME	

      # - name: Restart host
      #   run: |	
      #     sudo shutdown -r +1 "System will reboot in 1 minutes"	
